[package]
name = "pios"
version = "0.1.0"
edition = "2024"
description = "A small command-line OS for the Raspberry Pi 4, written in Rust"
publish = false

[[bin]]
name = "pios"
path = "src/main.rs"
test = false
bench = false

[dependencies]
pios-abi = { path = "abi" }
pios-bootfs = { path = "bootfs" }
pios-pl011 = { path = "pl011" }
pios-textconsole = { path = "textconsole" }

[build-dependencies]
pios-bootfs = { path = "bootfs", features = ["builder"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
codegen-units = 1
debug = true
