[build]
target = "aarch64-unknown-none-softfloat"

[target.aarch64-unknown-none-softfloat]
rustflags = [
    # BCM2711 = 4x Cortex-A72.
    "-C", "target-cpu=cortex-a72",
    # The MMU is off, so all memory is treated as Device memory and any
    # unaligned access faults. Stop LLVM from emitting unaligned loads/stores.
    "-C", "target-feature=+strict-align",
]
