#!/usr/bin/env python3
"""Generate textconsole/src/font.rs from a fixed-width 8-pixel-wide BDF font.

    tools/font/gen-font.py tools/font/spleen-8x16.bdf > textconsole/src/font.rs

Only printable ASCII (0x20-0x7E) is kept. Each glyph becomes HEIGHT bytes,
one per row, most significant bit = leftmost pixel.
"""
import sys

FIRST, LAST = 0x20, 0x7E


def parse(path):
    header, glyphs = [], {}
    width = height = descent = None
    with open(path) as f:
        lines = iter(f.read().splitlines())
    for line in lines:
        if line.startswith("COMMENT"):
            header.append(line[len("COMMENT"):].strip())
        elif line.startswith("FONTBOUNDINGBOX"):
            width, height, _, descent = map(int, line.split()[1:])
        elif line.startswith("STARTCHAR"):
            code, bbx = None, None
            for line in lines:
                if line.startswith("ENCODING"):
                    code = int(line.split()[1])
                elif line.startswith("BBX"):
                    bbx = list(map(int, line.split()[1:]))
                elif line == "BITMAP":
                    break
            rows = []
            for line in lines:
                if line == "ENDCHAR":
                    break
                rows.append(int(line, 16))
            if code is not None and FIRST <= code <= LAST:
                glyphs[code] = place(rows, bbx, width, height, descent)
    assert width == 8, "only 8-pixel-wide fonts are supported"
    missing = [c for c in range(FIRST, LAST + 1) if c not in glyphs]
    assert not missing, f"missing glyphs: {missing}"
    return header, height, glyphs


def place(rows, bbx, width, height, descent):
    """Position a glyph's bitmap within the font's bounding box."""
    w, h, xoff, yoff = bbx
    cell = [0] * height
    top = height - (h + yoff - descent)  # row of the glyph's first line
    for i, bits in enumerate(rows):
        bits >>= ((w + 7) // 8) * 8 - w  # right-align the w pixels
        cell[top + i] = (bits << (width - w - xoff)) & 0xFF
    return cell


def main():
    header, height, glyphs = parse(sys.argv[1])
    print("//! Bitmap font for the framebuffer console, generated by")
    print("//! tools/font/gen-font.py. Do not edit by hand.")
    print("//!")
    for line in header:
        if line not in ("/*", "*/"):
            print(f"//! {line.lstrip('* ').rstrip()}".rstrip())
    print("//!")
    print("//! Redistribution and use in source and binary forms, with or without")
    print("//! modification, are permitted provided that the following conditions")
    print("//! are met: redistributions of source code must retain the above")
    print("//! copyright notice, this list of conditions and the following")
    print("//! disclaimer; redistributions in binary form must reproduce the")
    print("//! above copyright notice, this list of conditions and the following")
    print("//! disclaimer in the documentation and/or other materials provided")
    print("//! with the distribution. See tools/font/LICENSE.spleen.")
    print()
    print("pub const WIDTH: usize = 8;")
    print(f"pub const HEIGHT: usize = {height};")
    print(f"pub const FIRST: u8 = {FIRST:#04x};")
    print(f"pub const LAST: u8 = {LAST:#04x};")
    print()
    print("/// One glyph per character from FIRST to LAST: a byte per row, most")
    print("/// significant bit leftmost.")
    print("#[rustfmt::skip]")
    print(f"pub static GLYPHS: [[u8; HEIGHT]; {LAST - FIRST + 1}] = [")
    for code in range(FIRST, LAST + 1):
        row = ", ".join(f"0x{b:02x}" for b in glyphs[code])
        name = repr(chr(code))
        print(f"    [{row}], // {name}")
    print("];")


if __name__ == "__main__":
    main()
